---
title: "AIED 2015 - Notes on NLP"
author: "Sameer Bhatnagar"
date: "June 26, 2015"
output: html_document
layout: post
tags: [AIED, NLP]
permalink: aied2015nlp
comments: yes
---
The two themes that I payed closed attention to at the AIED 2015 conference in Madrid were i) Affect, Motivation, and Engagement, and ii) Natural Language Approaches.

## NLP
Natural Language Processing (NLP) based approaches included work by:
<!--more-->
  + An impressive demo of Readerbench, by Mihai Dascalu, which combines the text cohesion indices of Coh-Metrix, with topic models (for french as well as english languages),  in order to examine self-explanation texts (to predict reading comprehension) and chat data (to measure collaboration)
  
  + Albacete, Jordan and Katz, from the University of Pittsburgh, looking at RIMAC, a dialog based intelligent tutoring system (ITS) which looked at different types of feedback in the context of conceptual physics. 
  
  + Suleman and Ikeda looking at Negotiation Driven Learning, where the ITS has an open learner model, and a tutor-agent engages in a rule riven dialog when the student expresses disagreement with the system's student model. 
  
  + Huang and Mostow comparing distractors in multiple choice cloze questions, generated either by humans, or automatically by their toold DQGen. 
  
  + Poster by Sorour, Goda, and Mine, from Kyushu University in Japan, which used pre,during, and post-instructional reflective writing texts to predict final grades in courses, using PLSA and LDA (64% accuracy)
  
  + Poster by Douglas S. and Heffernan's addition to the Assistments platform, called PeerAssist, which will have students explain their answer in a algebra ITS. 
  
  + Poster by Sharipova and MaCalla on the UMKA project, which provides students with a visualization of which students agree and disgree with them (through semantic distance measures) in comments on case-studies
  
  + Ezen-Can and Boyer, from the NC State Learn Dialog Group, which measured the performance of _unsupervised_ classification of dialog acts in a Java based ITS.
  
  + Blanchard & D'Mello's work comparing the performance of automatic speech recognizers in noisy classroom environments for automatic dilog analysis.
  
  + Hughes and Hastings who take a supervised machine learning approach for the hollistic evaluation of scientific essays, specifically looking for the student's ability to create causal links.
  
  + The half day workshop on NLP for EDM, given by Scott Crossley, Laura Allen, and Danielle McNamarra introduced the tools Coh-Metrix, TAACO, TERA, SiNLP and TAALES. Each shoud be explored further. Laura Allen described a study on prior content knowledge we could replicate. The main lesson learned was that NLP tools provide richer features (semantic, syntactical and lexical) which can then better inform conventional machine learning algorithms
  